spring:
  datasource: # 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fresh?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 159357
    
  http:
    encoding:
      force: true
      charset: utf-8
      
  session:
    store-type: redis
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 8
  
  mail:
    host: smtp.qq.com
    username: 834812608@qq.com
    password: jgwfakfhqxkvbcdg
    port: 465
    protocol: smtp
    properties: 
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            
# mybatis配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: cn.swan.fresh.user.entity # 需要扫描的启用别名的类所在的包
  
eureka:
  client:
    service-url: 
      defaultZone: http://swan:123456@127.0.0.1:6868/eureka
   